# Generated by Django 4.2.13 on 2024-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="tat",
            field=models.CharField(max_length=100),
        ),
    ]
