# Generated by Django 4.2.1 on 2024-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_test_tat"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="iso_certificate_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="iso_certificate_symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="open_24_hours",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="open_days",
            field=models.CharField(
                blank=True,
                default="Mondday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
