# Generated by Django 4.2.1 on 2024-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_service_closing_time_service_iso_certificate_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="other_time",
            field=models.TextField(blank=True, null=True),
        ),
    ]
