# Generated by Django 4.2.13 on 2024-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240714_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
