# Generated by Django 4.2.13 on 2024-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_test_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="testset",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
