# Generated by Django 4.2.13 on 2024-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_testset_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="tz_std_tariff",
            field=models.IntegerField(default=0),
        ),
    ]
