# Generated by Django 4.2.13 on 2024-07-17 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_test_tz_std_tariff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="unit",
        ),
    ]
