# Generated by Django 4.2.13 on 2024-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_test_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='base_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='base_cost_currency',
            field=models.CharField(default='TSZ', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='cost_per_km',
            field=models.FloatField(default=0),
        ),
    ]
