# Generated by Django 4.2.13 on 2024-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_organization_base_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
