# Generated by Django 4.2.13 on 2024-07-06 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="test_set",
        ),
    ]
