# Generated by Django 4.2.1 on 2024-07-11 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0003_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="test_sets",
            new_name="tests",
        ),
    ]
