# Generated by Django 4.2.1 on 2024-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_service_other_time"),
        ("request", "0004_rename_test_sets_favorite_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="tests",
            field=models.ManyToManyField(related_name="favorite_tests", to="main.test"),
        ),
    ]
