# Generated by Django 4.2.13 on 2024-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_favorite_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
