# Generated by Django 4.2.13 on 2024-07-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_request_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='unit',
        ),
    ]
