# Generated by Django 4.2.13 on 2024-07-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_unit'),
        ('request', '0007_remove_request_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tests',
        ),
        migrations.AddField(
            model_name='request',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.test'),
        ),
        migrations.AddField(
            model_name='request',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
