# Generated by Django 4.2.13 on 2024-07-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_remove_test_unit"),
        ("request", "0008_remove_request_tests_request_test_request_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="test",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.test"
            ),
            preserve_default=False,
        ),
    ]
