# Generated by Django 4.2.13 on 2024-07-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_test_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0009_alter_request_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphanumeric_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('insurance_membership_id', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('collection_home', models.TextField(blank=True, null=True)),
                ('collection_distance', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_fee', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
                ('requests', models.ManyToManyField(related_name='order_requests', to='request.request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
