# Generated by Django 4.2.13 on 2024-07-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='collection_centre',
            new_name='collection_center',
        ),
    ]
