# Generated by Django 4.2.13 on 2024-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_rename_collection_centre_order_collection_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
