# Generated by Django 4.2.13 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_order_date_of_birth_order_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
